business_unit                 = "it"
resource_group_name           = "rg"
virtual_network_name          = "vnet"
subnet_name                   = "mysubnet"
virtual_network_address_space = ["10.3.0.0/16", "10.4.0.0/16", "10.5.0.0/16"]
resource_group_location="eastus2"
db_name="mydb201"
db_storage_mb=5120
db_auto_grow_enable=true
